### ISSUE TITLE
How can I use this code with composer.

### ISSUE THREAD

**Issue by rohitkrs** [talandis/opay-gateway#1]
Hi,

Is there any command for composer to use this code. I tried some commands using composer require and also changed my composer.json but unable to make it running.
Please update your documentation so one can easily integrate it.

**Comment by talandis** [comment]
Hi,

Same method as installing any other package should work well. Try calling the following in CLI: `composer require talandis/opay-gateway`

**Comment by rohitkrs** [comment]
It worked. Thank talandis :)
